Reformatted with shfmt

diff --git a/bin/bcmnt b/bin/bcmnt
--- a/bin/bcmnt
+++ b/bin/bcmnt
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Header: /repo/local.cvs/per/bruce/bin/bcmnt,v 1.45 2020/02/07 19:35:35 bruce Exp $
+# $Header: /repo/local.cvs/per/bruce/bin/bcmnt,v 1.46 2021/10/26 19:26:08 bruce Exp $
 
 # Prefix codes (show the "scope" of variables):
 # gVar - global variable (may even be external to the script)
@@ -16,16 +16,16 @@
 # cVer - current version
 # cName - script's name
 
-function fUsage
+function fUsage()
 {
-	if [ $# -ne 0 ]; then
-		pod2text $0
-	else
-		pod2usage $0
-	fi
-	exit 1
-	
-	cat <<EOF
+    if [ $# -ne 0 ]; then
+        pod2text $0
+    else
+        pod2usage $0
+    fi
+    exit 1
+
+    cat <<EOF
 =pod
 
 =head1 bcmnt
@@ -148,155 +148,155 @@ encfs, encfsctl
 
 =head1 HISTORY
 
- $Revision: 1.45 $
- $Date: 2020/02/07 19:35:35 $ GMT 
+ $Revision: 1.46 $
+ $Date: 2021/10/26 19:26:08 $ GMT 
 
 =cut
 EOF
-	exit 1
+    exit 1
 } # fUsage
 
 # --------------------------------
-function fError
+function fError()
 {
-	# Usage:
-	#     fError pMsg [pLine [pErr]]
-	# Print the error message.  Then call fCleanUp, and exit
+    # Usage:
+    #     fError pMsg [pLine [pErr]]
+    # Print the error message.  Then call fCleanUp, and exit
 
-	local pMsg="$1"
-	local pLine=$2
-	local pErr=$3
+    local pMsg="$1"
+    local pLine=$2
+    local pErr=$3
 
-	fLog crit "$pMsg" $pLine $pErr
-	fUsage
+    fLog crit "$pMsg" $pLine $pErr
+    fUsage
 } # fError
 
 # ------------------
-function fLog
+function fLog()
 {
-	# Usage:
-	#     gErr=8801		# optional
-	#     fLog notice "Just testing" $LINENO 8
-	# pLevel - emerg alert crit err warning notice info debug
+    # Usage:
+    #     gErr=8801		# optional
+    #     fLog notice "Just testing" $LINENO 8
+    # pLevel - emerg alert crit err warning notice info debug
 
-	local pLevel=$1
-	local pMsg="$2"
-	# optional
-	local pLine=$3
-	# optional
-	local pErr=$4
+    local pLevel=$1
+    local pMsg="$2"
+    # optional
+    local pLine=$3
+    # optional
+    local pErr=$4
 
-	local tVerbose=""
-	local tErr=""
-	if [ -n "$pErr" ]; then
-		tErr="$pErr"
-	fi
-	if [ $gErr -ne 0 ]; then
-		tErr="$tErr,$gErr"
-	fi
-	if [ -n "$tErr" ]; then
-		tErr="($tErr)"
-	fi
+    local tVerbose=""
+    local tErr=""
+    if [ -n "$pErr" ]; then
+        tErr="$pErr"
+    fi
+    if [ $gErr -ne 0 ]; then
+        tErr="$tErr,$gErr"
+    fi
+    if [ -n "$tErr" ]; then
+        tErr="($tErr)"
+    fi
 
-	local tLine=""
-	if [ -n "$pLine" ]; then
-		tLine="[$pLine]"
-	fi
+    local tLine=""
+    if [ -n "$pLine" ]; then
+        tLine="[$pLine]"
+    fi
 
-	echo "${cName} $pLevel: $pMsg $tLine$tErr" 1>&2
+    echo "${cName} $pLevel: $pMsg $tLine$tErr" 1>&2
 } # fLog
 
 # ------------------
-function fCreateDir
+function fCreateDir()
 {
-	local pDir=$1
+    local pDir=$1
 
-	if [ -d $cTop/.$pDir.ecfs ]; then
-		fError "$cTop/.$pDir.ecfs already exists" $LINENO
-	fi
-	
-	if [ ! -d $cTop/$pDir ]; then
-		mkdir -p $cTop/$pDir
-	fi
-	if [ ! -d $cTop/$pDir ]; then
-		fError "Could not create: $cTop/$pDir" $LINENO
-	fi
+    if [ -d $cTop/.$pDir.ecfs ]; then
+        fError "$cTop/.$pDir.ecfs already exists" $LINENO
+    fi
 
-	fLog info "Create $pDir" $LINENO
-	encfs --standard $cTop/.$pDir.ecfs $cTop/$pDir
-	date >$cTop/$pDir/mounted
+    if [ ! -d $cTop/$pDir ]; then
+        mkdir -p $cTop/$pDir
+    fi
+    if [ ! -d $cTop/$pDir ]; then
+        fError "Could not create: $cTop/$pDir" $LINENO
+    fi
 
-	exit 0
+    fLog info "Create $pDir" $LINENO
+    encfs --standard $cTop/.$pDir.ecfs $cTop/$pDir
+    date >$cTop/$pDir/mounted
+
+    exit 0
 } # fCreateDir
 
 # ------------------
-function fMount
+function fMount()
 {
-	local pDir=$1
+    local pDir=$1
 
-	if [ -f $cTop/$pDir/mounted ]; then
-		fLog info "$pDir is already mounted" $LINENO
-		return 0
-	fi
-	if [ ! -d $cTop/.$pDir.ecfs ]; then
-		fError "Not found: $cTop/.$pDir.ecfs" $LINENO
-	fi
-	if [ ! -d $cTop/$pDir ]; then
-		mkdir -p $cTop/$pDir
-	fi
-	if [ ! -d $cTop/$pDir ]; then
-		fError "Could not create: $cTop/$pDir" $LINENO
-	fi
+    if [ -f $cTop/$pDir/mounted ]; then
+        fLog info "$pDir is already mounted" $LINENO
+        return 0
+    fi
+    if [ ! -d $cTop/.$pDir.ecfs ]; then
+        fError "Not found: $cTop/.$pDir.ecfs" $LINENO
+    fi
+    if [ ! -d $cTop/$pDir ]; then
+        mkdir -p $cTop/$pDir
+    fi
+    if [ ! -d $cTop/$pDir ]; then
+        fError "Could not create: $cTop/$pDir" $LINENO
+    fi
 
-	fLog info "Mount $pDir" $LINENO
-	if [ $gpSamePass -eq 1 ]; then
-		echo $cPass | encfs --stdinpass $gpTimeout $cTop/.$pDir.ecfs $cTop/$pDir
-	else
-		encfs --extpass="$cExtPass Password: " $gpTimeout $cTop/.$pDir.ecfs $cTop/$pDir
-	fi
-	if [ ! -f $cTop/$pDir/mounted ]; then
-		fError "Could not mount: $cTop/$pDir" $LINENO
-	fi
+    fLog info "Mount $pDir" $LINENO
+    if [ $gpSamePass -eq 1 ]; then
+        echo $cPass | encfs --stdinpass $gpTimeout $cTop/.$pDir.ecfs $cTop/$pDir
+    else
+        encfs --extpass="$cExtPass Password: " $gpTimeout $cTop/.$pDir.ecfs $cTop/$pDir
+    fi
+    if [ ! -f $cTop/$pDir/mounted ]; then
+        fError "Could not mount: $cTop/$pDir" $LINENO
+    fi
 } # fMount
 
 # ------------------
-function fUnmount
+function fUnmount()
 {
-	local pDir=$1
+    local pDir=$1
 
-	if [ ! -f $cTop/$pDir/mounted ]; then
-		fLog info "$pDir is already unmounted" $LINENO
-		return 0
-	fi
-	fLog info "Unmount $pDir" $LINENO
-	fusermount -u $cTop/$pDir
+    if [ ! -f $cTop/$pDir/mounted ]; then
+        fLog info "$pDir is already unmounted" $LINENO
+        return 0
+    fi
+    fLog info "Unmount $pDir" $LINENO
+    fusermount -u $cTop/$pDir
 } # fUnmount
 
 # ------------------
-function fList
+function fList()
 {
-	cd $cTop
-	fLog info "List dirs:" $LINENO
-	for tDir in $('ls' -d .*.ecfs 2>/dev/null); do
-		tDir=${tDir#.}
-		tDir=${tDir%.ecfs}
-		echo -n $cTop/$tDir
-		if [ -f $tDir/mounted ]; then
-			echo -e "\t mounted"
-		else
-			echo -e "\t not mounted"
-		fi
-	done
+    cd $cTop
+    fLog info "List dirs:" $LINENO
+    for tDir in $('ls' -d .*.ecfs 2>/dev/null); do
+        tDir=${tDir#.}
+        tDir=${tDir%.ecfs}
+        echo -n $cTop/$tDir
+        if [ -f $tDir/mounted ]; then
+            echo -e "\t mounted"
+        else
+            echo -e "\t not mounted"
+        fi
+    done
 
-	if [ -n "$gpVerbose" ]; then
-		for tDir in $cTop/.*.ecfs; do
-			echo '____________________'
-			fLog info "List $tDir:" $LINENO
-			encfsctl $tDir
-		done
-	fi
+    if [ -n "$gpVerbose" ]; then
+        for tDir in $cTop/.*.ecfs; do
+            echo '____________________'
+            fLog info "List $tDir:" $LINENO
+            encfsctl $tDir
+        done
+    fi
 
-	exit 0
+    exit 0
 } # fList
 
 # ==================================================
@@ -315,7 +315,7 @@ export gErr=0
 
 # -------------------
 # Define the version number for this script
-export cVer='$Revision: 1.45 $'
+export cVer='$Revision: 1.46 $'
 cVer=${cVer#*' '}
 cVer=${cVer%' '*}
 
@@ -326,7 +326,7 @@ export cTop=$HOME/bc
 # -------------------
 # Get Options Section
 if [ $# -eq 0 ]; then
-	fError "Missing options." $LINENO
+    fError "Missing options." $LINENO
 fi
 
 export gpMountAll=0
@@ -340,115 +340,115 @@ export gpTimeout=""
 export gpList=0
 export gpFileList=""
 while getopts :muM:U:C:agt:lhvx tArg; do
-	case $tArg in
-		m)	gpMountAll=1;;
-		u)	gpUnmountAll=1;;
-		M)	gpMount="$gpMount $OPTARG";;
-		U)	gpUnmount="$gpUnmount $OPTARG";;
-		C)	gpCreate=$OPTARG;;
-		a)	gpSamePass=1;;
-		g)	gpGUIPass=1;;
-		t)	gpTimeout="--idle=$OPTARG";;
-		l)	gpList=1;;
+    case $tArg in
+        m) gpMountAll=1 ;;
+        u) gpUnmountAll=1 ;;
+        M) gpMount="$gpMount $OPTARG" ;;
+        U) gpUnmount="$gpUnmount $OPTARG" ;;
+        C) gpCreate=$OPTARG ;;
+        a) gpSamePass=1 ;;
+        g) gpGUIPass=1 ;;
+        t) gpTimeout="--idle=$OPTARG" ;;
+        l) gpList=1 ;;
 
-		h)	fUsage long;;
-		v)	gpVerbose="-v";;
-		x)	let gpDebug=gpDebug+1;;
-		:)	fError "Value required for option: $OPTARG" $LINENO;;
-		\?)	fError "Unknown option: $OPTARG" $LINENO;;
-	esac
+        h) fUsage long ;;
+        v) gpVerbose="-v" ;;
+        x) let gpDebug=gpDebug+1 ;;
+        :) fError "Value required for option: $OPTARG" $LINENO ;;
+        \?) fError "Unknown option: $OPTARG" $LINENO ;;
+    esac
 done
 let tOptInd=OPTIND-1
 shift $tOptInd
 if [ $# -ne 0 ]; then
-	gpFileList="$*"
+    gpFileList="$*"
 fi
 
 # -------------------
 # Validate Options Section
 
 if [ $(whoami) = "root" ]; then
-	fError "Do not run as root user" $LINENO
+    fError "Do not run as root user" $LINENO
 fi
 
 which encfs >/dev/null
 if [ $? -ne 0 ]; then
-	fError "encfs is not installed!" $LINENO
+    fError "encfs is not installed!" $LINENO
 fi
 
 if [ $gpMountAll -eq 1 -a $gpUnmountAll -eq 1 ]; then
-	fError "You cannot mount and unmount all at the same time." $LINENO
+    fError "You cannot mount and unmount all at the same time." $LINENO
 fi
 
 if [ $gpMountAll -eq 1 -o $gpUnmountAll -eq 1 ]; then
-	if [ -n "$gpMount" -o -n "$gpUnmount" ]; then
-		fError "-M or -U options cannot be used with -m or -u options." $LINENO
-	fi
+    if [ -n "$gpMount" -o -n "$gpUnmount" ]; then
+        fError "-M or -U options cannot be used with -m or -u options." $LINENO
+    fi
 fi
 
 export cExtPass=""
 if [ -x /lib/cryptsetup/askpass ]; then
-	cExtPass=/lib/cryptsetup/askpass
+    cExtPass=/lib/cryptsetup/askpass
 fi
 if [ $gpGUIPass -eq 1 -a -x /usr/bin/ssh-askpass ]; then
-	cExtPass=/usr/bin/ssh-askpass
+    cExtPass=/usr/bin/ssh-askpass
 fi
 if [ -z "$cExtPass" ]; then
-	fError "Could not find a password prompt program." $LINENO
+    fError "Could not find a password prompt program." $LINENO
 fi
 
 # -------------------
 # Functional Section
 
 if [ $gpList -eq 1 ]; then
-	fList
-	exit 0
+    fList
+    exit 0
 fi
 
 if [ -n "$gpCreate" ]; then
-	fCreateDir $gpCreate
-	exit 0
+    fCreateDir $gpCreate
+    exit 0
 fi
 
 export cPass=""
 if [ -n "$gpMount" -o $gpMountAll -eq 1 ]; then
-	if [ $gpSamePass -eq 1 ]; then
-		cPass="$($cExtPass 'Common Password: ')"
-	fi
+    if [ $gpSamePass -eq 1 ]; then
+        cPass="$($cExtPass 'Common Password: ')"
+    fi
 fi
 
 if [ -n "$gpMount" ]; then
-	for tDir in $gpMount; do
-		fMount $tDir
-	done
+    for tDir in $gpMount; do
+        fMount $tDir
+    done
 fi
 
 if [ -n "$gpUnmount" ]; then
-	for tDir in $gpUnmount; do
-		fUnmount $tDir
-	done
+    for tDir in $gpUnmount; do
+        fUnmount $tDir
+    done
 fi
 
 if [ $gpMountAll -eq 1 ]; then
-	cd $cTop
-	for tDir in $('ls' -d .*.ecfs 2>/dev/null); do
-		tDir=${tDir#.}
-		tDir=${tDir%.ecfs}
-		if [ -f $tDir/mounted ]; then
-			fLog info "$tDir is already mounted" $LINENO
-		else
-			fMount $tDir
-		fi
-	done
-	exit 0
+    cd $cTop
+    for tDir in $('ls' -d .*.ecfs 2>/dev/null); do
+        tDir=${tDir#.}
+        tDir=${tDir%.ecfs}
+        if [ -f $tDir/mounted ]; then
+            fLog info "$tDir is already mounted" $LINENO
+        else
+            fMount $tDir
+        fi
+    done
+    exit 0
 fi
 
 if [ $gpUnmountAll -eq 1 ]; then
-	cd $cTop
-	for tDir in $('ls' */mounted 2>/dev/null); do
-		fUnmount ${tDir%/mounted}
-	done
-	exit 0
+    cd $cTop
+    for tDir in $('ls' */mounted 2>/dev/null); do
+        fUnmount ${tDir%/mounted}
+    done
+    exit 0
 fi
 
 exit 0
diff --git a/bin/cvs-html-diff b/bin/cvs-html-diff
--- a/bin/cvs-html-diff
+++ b/bin/cvs-html-diff
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ $# -ne 3 ]; then
-	cat <<EOF
+    cat <<EOF
 Usage:
 	cvs-html-diff -rN.N File.html DiffFile.html
 
@@ -10,7 +10,7 @@ N.N version of File and the current file.  This works best for xhtml
 files that have been formatted with tidy.
 
 EOF
-	exit 1
+    exit 1
 fi
 
 # -----------------
@@ -23,12 +23,12 @@ tTmpFile=~/tmp/diff.tmp
 # -----------------
 # Validate
 if [ ! -r $pFile ]; then
-	echo "Error: can not read $pFile"
-	exit 1
+    echo "Error: can not read $pFile"
+    exit 1
 fi
 if [ $pFile = $pDiffFile ]; then
-	echo "NewFile can not be the same as DiffFile"
-	exit 1
+    echo "NewFile can not be the same as DiffFile"
+    exit 1
 fi
 
 # -----------------
diff --git a/bin/dump-to-from-s3 b/bin/dump-to-from-s3
--- a/bin/dump-to-from-s3
+++ b/bin/dump-to-from-s3
@@ -22,17 +22,18 @@ fi
 PS3="Functional area? "
 echo
 select pFunctional in QUIT HELP prod qa eng ops; do
-	case $pFunctional in
-		QUIT)	exit 1;;
-		HELP)	cat <<EOF
+    case $pFunctional in
+        QUIT) exit 1 ;;
+        HELP)
+            cat <<EOF
 prod - prod* db dumps
 qa   - sit* db dumps
 eng  - dit* or dev* db dumps
 ops  - misc dumps
 EOF
-		;;
-		*)	break;;
-	esac
+            ;;
+        *) break ;;
+    esac
 done
 
 # ----------------------
@@ -41,22 +42,23 @@ echo "S3 Path: $tRepo/$pFunctional/$tDir"
 PS3="Direction? "
 echo
 select pUpDown in QUIT HELP up down; do
-	case $pFunctional in
-		QUIT)	exit 1;;
-		HELP)	cat <<EOF
+    case $pFunctional in
+        QUIT) exit 1 ;;
+        HELP)
+            cat <<EOF
 up   - Upload the FILE in current dir to 
 down - Download the FILE in from S3 to the current dir
 EOF
-		;;
-		*)	break;;
-	esac
+            ;;
+        *) break ;;
+    esac
 done
 
 # ----------------------
 pFile=$1
 if [ $pUpDown = "up" -a ! -r $pFile ]; then
-	echo "Could not read file: $pFile"
-	exit 1
+    echo "Could not read file: $pFile"
+    exit 1
 fi
 
 # ----------------------
diff --git a/bin/html-diff b/bin/html-diff
--- a/bin/html-diff
+++ b/bin/html-diff
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ $# -ne 3 ]; then
-	cat <<EOF
+    cat <<EOF
 Usage:
 	html-diff OldFile.html NewFile.html DiffFile.html
 
@@ -9,7 +9,7 @@ This script generates ins and del tags for the differences between
 OldFile and NewFile.  This works best for xhtml files that have been
 formatted with tidy.
 EOF
-	exit 1
+    exit 1
 fi
 
 # -----------------
@@ -22,24 +22,24 @@ tTmpFile=~/tmp/diff.tmp
 # -----------------
 # Validate
 if [ ! -r $pOldFile ]; then
-	echo "Error: can not read $pOldFile"
-	exit 1
+    echo "Error: can not read $pOldFile"
+    exit 1
 fi
 if [ ! -r $pNewFile ]; then
-	echo "Error: can not read $pNewFile"
-	exit 1
+    echo "Error: can not read $pNewFile"
+    exit 1
 fi
 if [ $pOldFile = $pNewFile ]; then
-	echo OldFile can not be the same as NewFile
-	exit 1
+    echo OldFile can not be the same as NewFile
+    exit 1
 fi
 if [ $pOldFile = $pDiffFile ]; then
-	echo OldFile can not be the same as DiffFile
-	exit 1
+    echo OldFile can not be the same as DiffFile
+    exit 1
 fi
 if [ $pNewFile = $pDiffFile ]; then
-	echo NewFile can not be the same as DiffFile
-	exit 1
+    echo NewFile can not be the same as DiffFile
+    exit 1
 fi
 
 # -----------------
diff --git a/bin/sshagent b/bin/sshagent
--- a/bin/sshagent
+++ b/bin/sshagent
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Id: sshagent,v 1.58 2015/07/19 03:30:07 bruce Exp $
+# $Id: sshagent,v 1.59 2021/10/26 19:26:12 bruce Exp $
 
 # Note: Because this script is usually sourced, exits and functions
 # are not used.  So that is why the "if" logic is so messy, with
@@ -13,33 +13,36 @@ pHelp=0
 pKill=0
 pScript=0
 while getopts :'hksx' tArg; do
-	case $tArg in
-		a)	pAdd=1;;
-		h)	pHelp=1;;
-		k)	pKill=1
-			pScript=1
-		;;
-		s)	pScript=1;;
-		x)	pDebug=1;;
-		?)	gErr=2
-			echo "Error: Unknown option: -$OPTARG [$gErr]"
-		;;
-		*)	gErr=3
-			echo "Error: Unknown option: $tArg [$gErr]"
-		;;
-	esac
+    case $tArg in
+        a) pAdd=1 ;;
+        h) pHelp=1 ;;
+        k)
+            pKill=1
+            pScript=1
+            ;;
+        s) pScript=1 ;;
+        x) pDebug=1 ;;
+        ?)
+            gErr=2
+            echo "Error: Unknown option: -$OPTARG [$gErr]"
+            ;;
+        *)
+            gErr=3
+            echo "Error: Unknown option: $tArg [$gErr]"
+            ;;
+    esac
 done
 let OPTIND=OPTIND-1
 shift $OPTIND
 pParm=""
 if [ $# -ne 0 ]; then
-	pParm="$*"
+    pParm="$*"
 fi
 
 if [ $pHelp -ne 0 -o $gErr -ne 0 ]; then
-	if [ $pHelp -ne 0 ]; then
-		pod2text $0
-		cat <<'EOF' >/dev/null
+    if [ $pHelp -ne 0 ]; then
+        pod2text $0
+        cat <<'EOF' >/dev/null
 =pod
 
 =head1 NAME
@@ -169,69 +172,69 @@ sshagent only works well with bash.
 
 (c) Copyright 2009 by TrustedID
 
-$Revision: 1.58 $ GMT 
+$Revision: 1.59 $ GMT 
 
 =cut
 
 EOF
-	fi
+    fi
 else
 
-# ------------------------------------------
+    # ------------------------------------------
 
-export cgAgentOwner=${cgAgentOwner:-$USER}
-export cgEnvDir=/home/$cgAgentOwner/.ssh
-export cgEnvFile=$cgEnvDir/.sshagent.env
+    export cgAgentOwner=${cgAgentOwner:-$USER}
+    export cgEnvDir=/home/$cgAgentOwner/.ssh
+    export cgEnvFile=$cgEnvDir/.sshagent.env
 
-# Create cgEnvDir if it doesn't exist
-if [ ! -d $cgEnvdir ]; then
-	mkdir -p $cgEnvDir
-fi
-# Keep the permissions low
-chown -R $cgAgentOwner $cgEnvDir
-chmod u=rwx,go= $cgEnvDir
-chmod -R go= $cgEnvDir
+    # Create cgEnvDir if it doesn't exist
+    if [ ! -d $cgEnvdir ]; then
+        mkdir -p $cgEnvDir
+    fi
+    # Keep the permissions low
+    chown -R $cgAgentOwner $cgEnvDir
+    chmod u=rwx,go= $cgEnvDir
+    chmod -R go= $cgEnvDir
 
-# Kill all agents.
-if [ $pKill -ne 0 ]; then
-	# Setup so that all agents will be killed and none started
-	echo "Killing all of your ssh-agents"
-	killall ssh-agent 2>/dev/null
-	rm -f $cgEnvFile 2>/dev/null
-fi
+    # Kill all agents.
+    if [ $pKill -ne 0 ]; then
+        # Setup so that all agents will be killed and none started
+        echo "Killing all of your ssh-agents"
+        killall ssh-agent 2>/dev/null
+        rm -f $cgEnvFile 2>/dev/null
+    fi
 
-# Check to see if an agent is running
-tSARunning=0
-if [ -f $cgEnvFile ]; then
-	chmod u+rwx,go= $cgEnvFile
-	. $cgEnvFile >/dev/null
-	ps -ef | egrep "($cgAgentOwner|$(id -u $cgAgentOwner))" | grep -v grep | grep $SSH_AGENT_PID >/dev/null 2>&1
-	if [ $? -eq 0 ]; then
-		tSARunning=1
-		ssh-add -l
-		if [ -n "$pParm" ]; then
-			ssh-add $pParm
-		fi
-		ssh-add -l
-	fi
-fi
-if [ $tSARunning -eq 0 ]; then
-	unset SSH_AUTH_SOCK SSH_AGENT_PID
-	if [ $pScript -eq 0 ]; then
-	    killall ssh-agent 2>/dev/null
-	    rm -f $cgEnvFile 2>/dev/null
-	fi
-fi
+    # Check to see if an agent is running
+    tSARunning=0
+    if [ -f $cgEnvFile ]; then
+        chmod u+rwx,go= $cgEnvFile
+        . $cgEnvFile >/dev/null
+        ps -ef | egrep "($cgAgentOwner|$(id -u $cgAgentOwner))" | grep -v grep | grep $SSH_AGENT_PID >/dev/null 2>&1
+        if [ $? -eq 0 ]; then
+            tSARunning=1
+            ssh-add -l
+            if [ -n "$pParm" ]; then
+                ssh-add $pParm
+            fi
+            ssh-add -l
+        fi
+    fi
+    if [ $tSARunning -eq 0 ]; then
+        unset SSH_AUTH_SOCK SSH_AGENT_PID
+        if [ $pScript -eq 0 ]; then
+            killall ssh-agent 2>/dev/null
+            rm -f $cgEnvFile 2>/dev/null
+        fi
+    fi
 
-if [ $pScript -eq 0 -a $tSARunning -eq 0 ]; then
-	echo Starting a new ssh-agent:
-	ssh-agent >$cgEnvFile
-	chmod u+rwx,go= $cgEnvFile
-	. $cgEnvFile >/dev/null
-	echo ssh-add $pParm
-	ssh-add $pParm
-fi
+    if [ $pScript -eq 0 -a $tSARunning -eq 0 ]; then
+        echo Starting a new ssh-agent:
+        ssh-agent >$cgEnvFile
+        chmod u+rwx,go= $cgEnvFile
+        . $cgEnvFile >/dev/null
+        echo ssh-add $pParm
+        ssh-add $pParm
+    fi
 
-unset tSARunning pScript pParm cgEnvDir cgEnvFile
+    unset tSARunning pScript pParm cgEnvDir cgEnvFile
 
 fi
diff --git a/bin/v4l2loopback-init b/bin/v4l2loopback-init
--- a/bin/v4l2loopback-init
+++ b/bin/v4l2loopback-init
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Header: /repo/local.cvs/per/bruce/bin/v4l2loopback-init,v 1.1 2020/11/19 19:55:46 bruce Exp $
+# $Header: /repo/local.cvs/per/bruce/bin/v4l2loopback-init,v 1.2 2021/10/26 19:26:12 bruce Exp $
 
 # Install this script:
 #   Put it in /etc/init.d
@@ -24,93 +24,93 @@
 # --------------------
 # Configure
 if [ -f /etc/default/v4l2loopback-init ]; then
-	. /etc/default/v4l2loopback-init
+    . /etc/default/v4l2loopback-init
 else
-	cVideo=4
-	cName="OBSCam"
-	cOptions="exclusive_caps=1"
+    cVideo=4
+    cName="OBSCam"
+    cOptions="exclusive_caps=1"
 fi
 
 # --------------------
 fStart()
 {
-	rootUser
-	lsmod 2>&1 | grep -q v4l2loopback
-	if [ $? -eq 0 ]; then
-		echo v4l2loopback is already running
-		exit 1
-	fi
-	modprobe v4l2loopback $cOptions devices=1 video_nr=$cVideo card_label="$cName"
-	fStatus
+    rootUser
+    lsmod 2>&1 | grep -q v4l2loopback
+    if [ $? -eq 0 ]; then
+        echo v4l2loopback is already running
+        exit 1
+    fi
+    modprobe v4l2loopback $cOptions devices=1 video_nr=$cVideo card_label="$cName"
+    fStatus
 }
 
 # --------------------
 fStop()
 {
-	rootUser
-	lsmod 2>&1 | grep -q v4l2loopback
-	if [ $? -eq 0 ]; then
-		rmmod v4l2loopback
-	fi
-	fStatus
+    rootUser
+    lsmod 2>&1 | grep -q v4l2loopback
+    if [ $? -eq 0 ]; then
+        rmmod v4l2loopback
+    fi
+    fStatus
 }
 
 # --------------------
 fStatus()
 {
-	# Status doesn't require root
-	tState=0
-	lsmod 2>&1 | grep -q v4l2loopback
-	if [ $? -eq 0 ]; then
-		let ++tState
-	fi
-	ls /dev | grep -q video4
-	if [ $? -eq 0 ]; then
-		let ++tState
-	fi
-	if [ $tState -eq 2 ]; then
-		echo v4l2loopback running: /dev/video$cVideo $cName
-	else
-		echo v4l2loopback is NOT running
-	fi
+    # Status doesn't require root
+    tState=0
+    lsmod 2>&1 | grep -q v4l2loopback
+    if [ $? -eq 0 ]; then
+        let ++tState
+    fi
+    ls /dev | grep -q video4
+    if [ $? -eq 0 ]; then
+        let ++tState
+    fi
+    if [ $tState -eq 2 ]; then
+        echo v4l2loopback running: /dev/video$cVideo $cName
+    else
+        echo v4l2loopback is NOT running
+    fi
 }
 
 # --------------------
 rootUser()
 {
-	if [ "$(whoami)" != "root" ]; then
-		echo "Error: you are not root user"
-		fUsage
-		exit 1
-	fi
+    if [ "$(whoami)" != "root" ]; then
+        echo "Error: you are not root user"
+        fUsage
+        exit 1
+    fi
 }
 
 # --------------------
 fUsage()
 {
-	echo $"Usage: $0 {start|stop|restart|status}"
+    echo $"Usage: $0 {start|stop|restart|status}"
 }
 
 # ========================================
 case "$1" in
-	start)
-		fStart
-	;;
-	stop)
-		fStop
-	;;
-	restart)
-		fStop
-		sleep 2
-		fStart
-	;;
-	status)
-		fStatus
-	;;
-	*)
-		fUsage
-		exit 1
-	;;
+    start)
+        fStart
+        ;;
+    stop)
+        fStop
+        ;;
+    restart)
+        fStop
+        sleep 2
+        fStart
+        ;;
+    status)
+        fStatus
+        ;;
+    *)
+        fUsage
+        exit 1
+        ;;
 esac
 
 exit 0
diff --git a/bin/versionsys b/bin/versionsys
--- a/bin/versionsys
+++ b/bin/versionsys
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Id: versionsys,v 1.4 2015/07/19 03:30:07 bruce Exp $
+# $Id: versionsys,v 1.5 2021/10/26 19:26:12 bruce Exp $
 
 # This script may be different for each server that it is installed
 # on, so don't just over-write it with newer versions.
@@ -9,8 +9,8 @@
 # or ownership changes, that CVS may make.
 
 if [ "$(whoami)" != "root" ]; then
-	echo "Error: You have to be root to run this."
-	exit 1
+    echo "Error: You have to be root to run this."
+    exit 1
 fi
 
 export CVSROOT=$(cat /CVS/Root)
diff --git a/bin/vid-archive b/bin/vid-archive
--- a/bin/vid-archive
+++ b/bin/vid-archive
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Header: /repo/local.cvs/per/bruce/bin/vid-archive,v 1.1 2018/02/25 21:37:30 bruce Exp $
+# $Header: /repo/local.cvs/per/bruce/bin/vid-archive,v 1.2 2021/10/26 19:26:12 bruce Exp $
 # Usage:
 #	vid-archive
 #	vid-archive /rel/archive/video/own
@@ -9,12 +9,12 @@ cArchive=/rel/archive/video/own
 cLog=$PWD/vid-archive.log
 
 if [ $# -ne 0 ]; then
-	cArchive=$1
+    cArchive=$1
 fi
 
 if [ ! -d $cArchive ]; then
-	echo "Error: Missing $cArchive"
-	exit 1
+    echo "Error: Missing $cArchive"
+    exit 1
 fi
 
 tCount1=$(find * -name '*.MP4' | wc -l)
@@ -28,42 +28,42 @@ echo "cp $PWD to $cArchive" | tee -a $cLog
 echo "Process: $tCount files" | tee -a $cLog
 
 for i in $(find * -name '*.MP4') $(find * -name '*.MOD'); do
-	if [ ! -f $i.info ]; then
-		exiftool $i >$i.info
-	fi
-	if [ ! -f $i.info ]; then
-		echo "Error: No info file for $i" | tee -a $cLog
-		continue
-	fi
-	tDate=$(grep 'Date.*Original' $i.info | awk '{gsub(":","-",$4); print $4}')
-	if [ -z "$tDate" ]; then
-		tDate=$(grep 'File Modification Date/Time' $i.info | awk '{gsub(":","-",$5); print $5}')
-	fi
-	if [ -z "$tDate" ]; then
-		echo "Error: could not get date for $i" | tee -a $cLog
-		continue
-	fi
-	tDiff=1
-	if [ ! -d $cArchive/$tDate ]; then
-		echo "mkdir $cArchive/$tDate" | tee -a $cLog
-		mkdir $cArchive/$tDate
-	fi
-	if [ -f  $cArchive/$tDate/${i##*/} ]; then
-		echo "diff -q $i $cArchive/$tDate/${i##*/}" | tee -a $cLog
-		diff -q $i $cArchive/$tDate/${i##*/} | tee -a $cLog
-		tDiff=$?
-		if [ $tDiff -eq 0 ]; then
-			echo -e "\t $i is already at $cArchive/$tDate" | tee -a $cLog
-		else
-			echo -e "\t Error: $i is different at $cArchive/$tDate" | tee -a $cLog
-			continue
-		fi
-	fi
-	if [ $tDiff -ne 0 ]; then
-		echo "cp -nv --perserve=all $i $cArchive/$tDate" | tee -a $cLog
-		cp -nv --preserve=all $i $cArchive/$tDate
-		cp -nv --preserve=all $i.info $cArchive/$tDate
-	fi
+    if [ ! -f $i.info ]; then
+        exiftool $i >$i.info
+    fi
+    if [ ! -f $i.info ]; then
+        echo "Error: No info file for $i" | tee -a $cLog
+        continue
+    fi
+    tDate=$(grep 'Date.*Original' $i.info | awk '{gsub(":","-",$4); print $4}')
+    if [ -z "$tDate" ]; then
+        tDate=$(grep 'File Modification Date/Time' $i.info | awk '{gsub(":","-",$5); print $5}')
+    fi
+    if [ -z "$tDate" ]; then
+        echo "Error: could not get date for $i" | tee -a $cLog
+        continue
+    fi
+    tDiff=1
+    if [ ! -d $cArchive/$tDate ]; then
+        echo "mkdir $cArchive/$tDate" | tee -a $cLog
+        mkdir $cArchive/$tDate
+    fi
+    if [ -f $cArchive/$tDate/${i##*/} ]; then
+        echo "diff -q $i $cArchive/$tDate/${i##*/}" | tee -a $cLog
+        diff -q $i $cArchive/$tDate/${i##*/} | tee -a $cLog
+        tDiff=$?
+        if [ $tDiff -eq 0 ]; then
+            echo -e "\t $i is already at $cArchive/$tDate" | tee -a $cLog
+        else
+            echo -e "\t Error: $i is different at $cArchive/$tDate" | tee -a $cLog
+            continue
+        fi
+    fi
+    if [ $tDiff -ne 0 ]; then
+        echo "cp -nv --perserve=all $i $cArchive/$tDate" | tee -a $cLog
+        cp -nv --preserve=all $i $cArchive/$tDate
+        cp -nv --preserve=all $i.info $cArchive/$tDate
+    fi
 done
 
 echo "See log file: $cLog"
diff --git a/bin/vid-cp2rel b/bin/vid-cp2rel
--- a/bin/vid-cp2rel
+++ b/bin/vid-cp2rel
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Header: /repo/local.cvs/per/bruce/bin/vid-cp2rel,v 1.1 2019/09/24 07:49:40 bruce Exp $
+# $Header: /repo/local.cvs/per/bruce/bin/vid-cp2rel,v 1.2 2021/10/26 19:26:12 bruce Exp $
 
 # Prefix codes (show the "scope" of variables):
 # gVar - global variable (may even be external to the script)
@@ -19,16 +19,16 @@
 # cCurDir - current directory
 
 # --------------------------------
-function fUsage
+function fUsage()
 {
-	if [ $# -ne 0 ]; then
-		pod2text $0
-	else
-		pod2usage $0
-	fi
-	gErr=1
-	exit 1
-	cat <<EOF >/dev/null
+    if [ $# -ne 0 ]; then
+        pod2text $0
+    else
+        pod2usage $0
+    fi
+    gErr=1
+    exit 1
+    cat <<EOF >/dev/null
 =pod
 
 =head1 NAME
@@ -164,79 +164,79 @@ You are cd'd in /home/video/skit/src/final and it has files:
 
 =head1 HISTORY
 
-$Revision: 1.1 $ $Date: 2019/09/24 07:49:40 $ GMT 
+$Revision: 1.2 $ $Date: 2021/10/26 19:26:12 $ GMT 
 
 =cut
 EOF
-	exit 1
+    exit 1
 } # fUsage
 
 # --------------------------------
-function fError
+function fError()
 {
-	# Usage:
-	#     fError pMsg [pLine [pErr]]
-	# Print the error message.  Then call fCleanUp, and exit
+    # Usage:
+    #     fError pMsg [pLine [pErr]]
+    # Print the error message.  Then call fCleanUp, and exit
 
-	local pMsg="$1"
-	local pLine=$2
-	local pErr=$3
+    local pMsg="$1"
+    local pLine=$2
+    local pErr=$3
 
-	fLog crit "$pMsg" $pLine $pErr
-	fUsage
+    fLog crit "$pMsg" $pLine $pErr
+    fUsage
 } # fError
 
 # ------------------
-function fLog
+function fLog()
 {
-	# Usage:
-	#     gErr=8801		# optional
-	#     fLog notice "Just testing" $LINENO 8
-	# pLevel - emerg alert crit err warning notice info debug
+    # Usage:
+    #     gErr=8801		# optional
+    #     fLog notice "Just testing" $LINENO 8
+    # pLevel - emerg alert crit err warning notice info debug
 
-	local pLevel=$1
-	local pMsg="$2"
-	# optional
-	local pLine=$3
-	# optional
-	local pErr=$4
+    local pLevel=$1
+    local pMsg="$2"
+    # optional
+    local pLine=$3
+    # optional
+    local pErr=$4
 
-	local tVerbose=""
-	local tErr=""
-	if [ -n "$pErr" ]; then
-		tErr="$pErr"
-	fi
-	if [ $gErr -ne 0 ]; then
-		tErr="$tErr,$gErr"
-	fi
-	if [ -n "$tErr" ]; then
-		tErr="($tErr)"
-	fi
+    local tVerbose=""
+    local tErr=""
+    if [ -n "$pErr" ]; then
+        tErr="$pErr"
+    fi
+    if [ $gErr -ne 0 ]; then
+        tErr="$tErr,$gErr"
+    fi
+    if [ -n "$tErr" ]; then
+        tErr="($tErr)"
+    fi
 
-	local tLine=""
-	if [ -n "$pLine" ]; then
-		tLine="[$pLine]"
-	fi
+    local tLine=""
+    if [ -n "$pLine" ]; then
+        tLine="[$pLine]"
+    fi
 
-	if [ $gpLog -eq 0 ]; then
-		echo "${cName}[$$] $pLevel: $pMsg $tLine$tErr" 1>&2
-	else
-		if [ -n "$gpVerbose" ]; then
-			tVerbose="-s"
-		fi
-		logger $tVerbose -i -t $cName -p local1.$pLevel "$pLevel: $pMsg $tLine$tErr"
-	fi
+    if [ $gpLog -eq 0 ]; then
+        echo "${cName}[$$] $pLevel: $pMsg $tLine$tErr" 1>&2
+    else
+        if [ -n "$gpVerbose" ]; then
+            tVerbose="-s"
+        fi
+        logger $tVerbose -i -t $cName -p local1.$pLevel "$pLevel: $pMsg $tLine$tErr"
+    fi
 } # fLog
 
 # =========================================
 # Main
-export	cBin cCurdir gErr gpDebug cName cVer gpVerbose PWD
+export cBin cCurdir gErr gpDebug cName cVer gpVerbose PWD
 
 # -------------------
 # Set current directory location in PWD and cCurDir, because with cron
 # jobs PWD is not set.
 if [ -z "$PWD" ]; then
-	PWD=$(pwd)
+    PWD=$(pwd)
 fi
 cCurDir=$PWD
 
@@ -254,7 +254,7 @@ gErr=0
 
 # -------------------
 # Define the version number for this script
-cVer='$Revision: 1.1 $'
+cVer='$Revision: 1.2 $'
 cVer=${cVer#*' '}
 cVer=${cVer%' '*}
 
@@ -264,64 +264,64 @@ cVer=${cVer%' '*}
 # -------------------
 # Get Options Section
 if [ $# -eq 0 ]; then
-	fError "Missing options." $LINENO
+    fError "Missing options." $LINENO
 fi
 gpFileList=""
 gpRelDir=""
 gpRunGetRel=0
 while getopts :d:uhlxv tArg; do
-	case $tArg in
-		d)	gpRelDir=$OPTARG;;
-		u)	gpRunGetRel=1;;
+    case $tArg in
+        d) gpRelDir=$OPTARG ;;
+        u) gpRunGetRel=1 ;;
 
-		h)	fUsage long;;
-		l)	gpLog=1;;
-		v)	gpVerbose="-v";;
-		x)	let gpDebug=gpDebug+1;;
-		:)	fError "Value required for option: $OPTARG" $LINENO;;
-		\?)	fError "Unknown option: $OPTARG" $LINENO;;
-	esac
+        h) fUsage long ;;
+        l) gpLog=1 ;;
+        v) gpVerbose="-v" ;;
+        x) let gpDebug=gpDebug+1 ;;
+        :) fError "Value required for option: $OPTARG" $LINENO ;;
+        \?) fError "Unknown option: $OPTARG" $LINENO ;;
+    esac
 done
 let tOptInd=OPTIND-1
 shift $tOptInd
 if [ $# -ne 0 ]; then
-	gpFileList="$*"
+    gpFileList="$*"
 fi
 
 # -------------------
 # Validate Options Section
 
 if [ -z "$gpFileList" ]; then
-	fError "Missing files" $LINENO
+    fError "Missing files" $LINENO
 fi
 
 tArchive=0
 case $gpRelDir in
-	arc|archive)
-		tArchive=1
-		tRelDir=/rel/archive/video/own/[YYYY-MM-DD]
-	;;
-	dev|develop|development)
-		tRelDir=/rel/development/video/[ProjectName]
-	;;
-	rel|release|released)
-		tRelDir=/rel/released/video/[ProjectName]
-	;;
-	*)	fError "Invalid -d option: $gpRelDir" $LINENO;;
+    arc | archive)
+        tArchive=1
+        tRelDir=/rel/archive/video/own/[YYYY-MM-DD]
+        ;;
+    dev | develop | development)
+        tRelDir=/rel/development/video/[ProjectName]
+        ;;
+    rel | release | released)
+        tRelDir=/rel/released/video/[ProjectName]
+        ;;
+    *) fError "Invalid -d option: $gpRelDir" $LINENO ;;
 esac
 
 export tProjectName=${PWD#/home/video/}
 if [ "$tProjectName" = "$PWD" ]; then
-	fError "You are not in a /home/video project dir" $LINENO
+    fError "You are not in a /home/video project dir" $LINENO
 fi
 export tProjectName=${tProjectName%%/*}
 
 if [ ! -d CVS ]; then
-	fError "You are not in a CVS working dir" $LINENO
+    fError "You are not in a CVS working dir" $LINENO
 fi
 
 if [ ! -d /mnt/usb-video/repo/video ]; then
-	fError "/mnt/usb-video is not mounted" $LINENO
+    fError "/mnt/usb-video is not mounted" $LINENO
 fi
 
 # -------------------
@@ -329,22 +329,22 @@ fi
 
 tDestDir=$tRelDir
 for tFile in $gpFileList; do
-	echo "Copying $tFile"
-	tFileVer=$(cvs log $tFile | grep head | sed 's/head: //')
-	tFileDate=$(cvs log -r$tFileVer $tFile | grep date: | awk '{print $2}')
-	tDestFile=$tProjectName_$tFileDate_$tFileVer_$tFileName
-	if [ $tArchive -eq 1 ]; then
-		tDestDir=$tRelDir/$tFileDate
-		mkdir -p $tDestDir 2>/dev/null
-	fi
+    echo "Copying $tFile"
+    tFileVer=$(cvs log $tFile | grep head | sed 's/head: //')
+    tFileDate=$(cvs log -r$tFileVer $tFile | grep date: | awk '{print $2}')
+    tDestFile=$tProjectName_$tFileDate_$tFileVer_$tFileName
+    if [ $tArchive -eq 1 ]; then
+        tDestDir=$tRelDir/$tFileDate
+        mkdir -p $tDestDir 2>/dev/null
+    fi
 
-	cvs add $tFile 2>/dev/null
-	if ! cvs commit -m "Copy to $tDistDir" $tFile; then
-		fError "cvs commit error with $tFile" $LINENO
-	fi
+    cvs add $tFile 2>/dev/null
+    if ! cvs commit -m "Copy to $tDistDir" $tFile; then
+        fError "cvs commit error with $tFile" $LINENO
+    fi
 
-	rsync -aP $tFile $tDistDir/$tDestFile
-	cat <<EOF | tee -a README.html >>$tDistDir/README.html
+    rsync -aP $tFile $tDistDir/$tDestFile
+    cat <<EOF | tee -a README.html >>$tDistDir/README.html
 
 $(date)
 Source: $PWD/$tFile
@@ -353,12 +353,12 @@ EOF
 done
 
 if [ $gpRunGetRel -eq 1 ]; then
-	cd $tRelDir
-	if [ $tArchive -eq 1 ]; then
-		getrel -uLl
-	else
-		getrel -uL
-	fi
+    cd $tRelDir
+    if [ $tArchive -eq 1 ]; then
+        getrel -uLl
+    else
+        getrel -uL
+    fi
 fi
 
 echo "See: README.html file for the list of copied files."
diff --git a/bin/vid-edit b/bin/vid-edit
--- a/bin/vid-edit
+++ b/bin/vid-edit
@@ -1,16 +1,16 @@
 #!/bin/bash
 
 # --------------------------------
-function fUsage
+function fUsage()
 {
-	if [ $# -ne 0 ]; then
-		pod2text $0
-	else
-		pod2usage $0
-	fi
-	exit 1
-	# See also: pod2html, and pod2man, pod2pdf, pod2md
-	cat <<EOF >/dev/null
+    if [ $# -ne 0 ]; then
+        pod2text $0
+    else
+        pod2usage $0
+    fi
+    exit 1
+    # See also: pod2html, and pod2man, pod2pdf, pod2md
+    cat <<EOF >/dev/null
 =pod
 
 =head1 NAME
@@ -146,143 +146,144 @@ kdenlive file's version.
 
 =head1 HISTORY
 
-$Revision: 1.22 $ $Date: 2021/08/18 23:12:21 $ GMT 
+$Revision: 1.23 $ $Date: 2021/10/26 19:26:13 $ GMT 
 
 =cut
 EOF
-	exit 1
+    exit 1
 } # fUsage
 
 # --------------------------------
-function fError
+function fError()
 {
-	# Usage:
-	#     fError pMsg [pLine [pErr]]
-	# Print the error message.  Then call fCleanUp, and exit
+    # Usage:
+    #     fError pMsg [pLine [pErr]]
+    # Print the error message.  Then call fCleanUp, and exit
 
-	local pMsg="$1"
-	local pLine=$2
-	local pErr=$3
+    local pMsg="$1"
+    local pLine=$2
+    local pErr=$3
 
-	fLog crit "$pMsg" $pLine $pErr
-	fUsage
+    fLog crit "$pMsg" $pLine $pErr
+    fUsage
 } # fError
 
 # ------------------
-function fLog
+function fLog()
 {
-	# Usage:
-	#     gErr=8801		# optional
-	#     fLog notice "Just testing" $LINENO 8
-	# pLevel - emerg alert crit err warning notice info debug
+    # Usage:
+    #     gErr=8801		# optional
+    #     fLog notice "Just testing" $LINENO 8
+    # pLevel - emerg alert crit err warning notice info debug
 
-	local pLevel=$1
-	local pMsg="$2"
-	# optional
-	local pLine=$3
-	# optional
-	local pErr=$4
+    local pLevel=$1
+    local pMsg="$2"
+    # optional
+    local pLine=$3
+    # optional
+    local pErr=$4
 
-	local tVerbose=""
-	local tErr=""
-	if [ -n "$pErr" ]; then
-		tErr="$pErr"
-	fi
-	if [ $gErr -ne 0 ]; then
-		tErr="$tErr,$gErr"
-	fi
-	if [ -n "$tErr" ]; then
-		tErr="($tErr)"
-	fi
+    local tVerbose=""
+    local tErr=""
+    if [ -n "$pErr" ]; then
+        tErr="$pErr"
+    fi
+    if [ $gErr -ne 0 ]; then
+        tErr="$tErr,$gErr"
+    fi
+    if [ -n "$tErr" ]; then
+        tErr="($tErr)"
+    fi
 
-	local tLine=""
-	if [ -n "$pLine" ]; then
-		tLine="[$pLine]"
-	fi
+    local tLine=""
+    if [ -n "$pLine" ]; then
+        tLine="[$pLine]"
+    fi
 
-	if [ $gpLog -eq 0 ]; then
-		echo "${cName}[$$] $pLevel: $pMsg $tLine$tErr" 1>&2
-	else
-		if [ -n "$gpVerbose" ]; then
-			tVerbose="-s"
-		fi
-		logger $tVerbose -i -t $cName -p local1.$pLevel "$pLevel: $pMsg $tLine$tErr"
-	fi
+    if [ $gpLog -eq 0 ]; then
+        echo "${cName}[$$] $pLevel: $pMsg $tLine$tErr" 1>&2
+    else
+        if [ -n "$gpVerbose" ]; then
+            tVerbose="-s"
+        fi
+        logger $tVerbose -i -t $cName -p local1.$pLevel "$pLevel: $pMsg $tLine$tErr"
+    fi
 } # fLog
 
 # ------------------
-function fFileCheck
+function fFileCheck()
 {
-	# Input: gpFile
-	# Ouput: gFileVer
-	if [ -z "$gpFile" ]; then
-		gFileVer=""
-		return
-	fi
+    # Input: gpFile
+    # Ouput: gFileVer
+    if [ -z "$gpFile" ]; then
+        gFileVer=""
+        return
+    fi
 
-	if [ ! -w $gpFile ]; then
-		if [ ! -w $gpFile.kdenlive ]; then
-			fError "Could not find $gpFile, or it is not writable." $LINENO
-		fi
-		gpFile=$gpFile.kdenlive
-	fi
+    if [ ! -w $gpFile ]; then
+        if [ ! -w $gpFile.kdenlive ]; then
+            fError "Could not find $gpFile, or it is not writable." $LINENO
+        fi
+        gpFile=$gpFile.kdenlive
+    fi
 
-	gFileVer=$(grep kdenliveversion $gpFile | sed 's/[<>]/ /g' | awk '{print $3}')
-	gFileVer=${gFileVer%.*}
+    gFileVer=$(grep kdenliveversion $gpFile | sed 's/[<>]/ /g' | awk '{print $3}')
+    gFileVer=${gFileVer%.*}
 
-	if [ -z "$gFileVer" ]; then
-		fError "kdenliveversion not found. Is $gpFile a kdenlive file?" $LINENO
-	fi
+    if [ -z "$gFileVer" ]; then
+        fError "kdenliveversion not found. Is $gpFile a kdenlive file?" $LINENO
+    fi
 } # fFileCheck
 
 # ------------------
-function fKLVer
+function fKLVer()
 {
-	# Input: gpVer, gFileVer, cLatestVer, cKLBin
-	# Output: gKLProg, gpVer, gFileVer
-	if [ ! -d $cKLBin ]; then
-		fError "Could not find directory: $cKLBin" $LINENO
-	fi
-	if [ -z "$gFileVer" ]; then
-		gFileVer=$cLatestVer
-	fi
-	if [ -z "$gpVer" ]; then
-		gpVer=$gFileVer
-	fi
+    # Input: gpVer, gFileVer, cLatestVer, cKLBin
+    # Output: gKLProg, gpVer, gFileVer
+    if [ ! -d $cKLBin ]; then
+        fError "Could not find directory: $cKLBin" $LINENO
+    fi
+    if [ -z "$gFileVer" ]; then
+        gFileVer=$cLatestVer
+    fi
+    if [ -z "$gpVer" ]; then
+        gpVer=$gFileVer
+    fi
 
-	case $gpVer in
-		16.11)	tUse=kdenlive-16.12-alpha1-x86_64.AppImage;;
-		16.12)	tUse=kdenlive-16.12-alpha1-x86_64.AppImage;;
-		17.04)	tUse=Kdenlive-17.04.1b-x86_64.AppImage;;
-		17.12)	tUse=Kdenlive-17.12.0d-x86_64.AppImage;;
-		18.12)	tUse=kdenlive-18.12.1-x86_64.appimage;;
-		19.04)	tUse=kdenlive-19.04.3-x86_64.appimage;;
-		19.08)	tUse=kdenlive-19.08.3-x86_64.appimage;;
-		19.12)	tUse=kdenlive-19.12.0a-x86_64.appimage;;
-		20.04)	tUse=kdenlive-20.04.0b-x86_64.appimage;;
-		20.12)	tUse=kdenlive-20.12.3a-x86_64.appimage;;
-		21.04)	tUse=kdenlive-21.04.3b-x86_64.appimage;;
-		*)	fError "No version available for $pVer. $cLatestVer is the lastest version. You will need to upgrade." $LINENO
-		;;
-	esac
-	gKLProg=$cKLBin/$tUse
-	if [ ! -x $gKLProg ]; then
-		fError "Not found: $gKLProg" $LINENO
-	fi
-	if [ "$gpVer" != "$gFileVer" ]; then
-		fLog warning "$gpVer is different from the file version: $gFileVer" $LINENO
-	fi
+    case $gpVer in
+        16.11) tUse=kdenlive-16.12-alpha1-x86_64.AppImage ;;
+        16.12) tUse=kdenlive-16.12-alpha1-x86_64.AppImage ;;
+        17.04) tUse=Kdenlive-17.04.1b-x86_64.AppImage ;;
+        17.12) tUse=Kdenlive-17.12.0d-x86_64.AppImage ;;
+        18.12) tUse=kdenlive-18.12.1-x86_64.appimage ;;
+        19.04) tUse=kdenlive-19.04.3-x86_64.appimage ;;
+        19.08) tUse=kdenlive-19.08.3-x86_64.appimage ;;
+        19.12) tUse=kdenlive-19.12.0a-x86_64.appimage ;;
+        20.04) tUse=kdenlive-20.04.0b-x86_64.appimage ;;
+        20.12) tUse=kdenlive-20.12.3a-x86_64.appimage ;;
+        21.04) tUse=kdenlive-21.04.3b-x86_64.appimage ;;
+        *)
+            fError "No version available for $pVer. $cLatestVer is the lastest version. You will need to upgrade." $LINENO
+            ;;
+    esac
+    gKLProg=$cKLBin/$tUse
+    if [ ! -x $gKLProg ]; then
+        fError "Not found: $gKLProg" $LINENO
+    fi
+    if [ "$gpVer" != "$gFileVer" ]; then
+        fLog warning "$gpVer is different from the file version: $gFileVer" $LINENO
+    fi
 } # fKLVer
 
 # ------------------
-function fCVSCheck
+function fCVSCheck()
 {
-	if [ $gpCVS -ne 1 ]; then
-		return
-	fi
+    if [ $gpCVS -ne 1 ]; then
+        return
+    fi
 
-	if [ ! -r CVS/Entries ]; then
-		cat <<EOF
+    if [ ! -r CVS/Entries ]; then
+        cat <<EOF
 		
 Error: there are no CVS directories in this directory. You need to
 add files to CVS, so that files can be versioned.
@@ -293,67 +294,67 @@ Recommend:
 	export CVS_RSH=ssh
 	export CVSUMASK=0003
 EOF
-		fError "To fix, add $gpFile to a CVS repository." $LINENO
-	fi
+        fError "To fix, add $gpFile to a CVS repository." $LINENO
+    fi
 
-	if grep ':ext:' CVS/Root ; then
-		ps -ef | grep ssh-agent
-		if [ $? -eq 0 ]; then
-			. sshagent -s
-		else
-			fLog warning "Things will go smoother if you start a sshagent" $LINENO
-		fi
-	else
-		tRoot=$(cat CVS/Root)
-		if [ ! -d $tRoot ]; then
-			fError "$tRoot is not mounted" $LINENO
-		fi
-	fi
+    if grep ':ext:' CVS/Root; then
+        ps -ef | grep ssh-agent
+        if [ $? -eq 0 ]; then
+            . sshagent -s
+        else
+            fLog warning "Things will go smoother if you start a sshagent" $LINENO
+        fi
+    else
+        tRoot=$(cat CVS/Root)
+        if [ ! -d $tRoot ]; then
+            fError "$tRoot is not mounted" $LINENO
+        fi
+    fi
 
-	if [ -z "$gpFile" ]; then
-		return
-	fi
-	if grep -q $gpFile CVS/Entries; then
-		# Commit the file
-		cvs commit -m "Updated with script vid-edit" $gpFile
-	else
-		fLog info "The file isn't versioned."
-		if [ $gpBatch -ne 0 ]; then
-			return
-		fi
-		read -p "Version the file? (y/n) "
-		if [ "$REPLY" = "y" ]; then
-			cvs add $gpFile
-			cvs commit -m "Added with script vid-edit"
-		fi
-	fi
+    if [ -z "$gpFile" ]; then
+        return
+    fi
+    if grep -q $gpFile CVS/Entries; then
+        # Commit the file
+        cvs commit -m "Updated with script vid-edit" $gpFile
+    else
+        fLog info "The file isn't versioned."
+        if [ $gpBatch -ne 0 ]; then
+            return
+        fi
+        read -p "Version the file? (y/n) "
+        if [ "$REPLY" = "y" ]; then
+            cvs add $gpFile
+            cvs commit -m "Added with script vid-edit"
+        fi
+    fi
 } # fCVSCheck
 
 # ------------------
-function fTag
+function fTag()
 {
-	if [ $gpCVS -ne 1 -o $gpBatch -eq 1 ]; then
-		return
-	fi
-	
-	echo
-	read -p "Was the video rendered (y/n)? "
-	if [ "$REPLY" != "y" ]; then
-		return
-	fi
-	tTag="rendered_${gpFile%.*}_$(date +%F)"
-	logtime "$tTag"
+    if [ $gpCVS -ne 1 -o $gpBatch -eq 1 ]; then
+        return
+    fi
 
-	echo
-	read -p "Tag the files with: $tTag (y/n)? "
-	if [ "$REPLY" != "y" ]; then
-		return
-	fi
+    echo
+    read -p "Was the video rendered (y/n)? "
+    if [ "$REPLY" != "y" ]; then
+        return
+    fi
+    tTag="rendered_${gpFile%.*}_$(date +%F)"
+    logtime "$tTag"
 
-	cd ..
-	cvs ci -m "$tTag"
-	cvs tag -F "$tTag"
-	cd -
+    echo
+    read -p "Tag the files with: $tTag (y/n)? "
+    if [ "$REPLY" != "y" ]; then
+        return
+    fi
+
+    cd ..
+    cvs ci -m "$tTag"
+    cvs tag -F "$tTag"
+    cd -
 } # fTag
 
 # ===================================================
@@ -380,33 +381,33 @@ export cKLBin=/usr/local/bin
 # -------------------
 # Get Options Section
 if [ $# -eq 0 ]; then
-	fError "Missing options." $LINENO
+    fError "Missing options." $LINENO
 fi
 export gpFile=""
 export gpCVS=1
 export gpVer=""
 export gpBatch=0
 while getopts :bclv:hLVx tArg; do
-	case $tArg in
-		b)	gpBatch=1;;
-		c)	gpCVS=0;;
-		l)	gpVer=cLatestVer;;
-		v)	gpVer=$OPTARG;;
+    case $tArg in
+        b) gpBatch=1 ;;
+        c) gpCVS=0 ;;
+        l) gpVer=cLatestVer ;;
+        v) gpVer=$OPTARG ;;
 
-		h)	fUsage long;;
-		L)	gpLog=1;;
-		V)	gpVerbose="-v";;
-		x)	let gpDebug=gpDebug+1;;
-		:)	fError "Value required for option: $OPTARG" $LINENO;;
-		\?)	fError "Unknown option: $OPTARG" $LINENO;;
-	esac
+        h) fUsage long ;;
+        L) gpLog=1 ;;
+        V) gpVerbose="-v" ;;
+        x) let gpDebug=gpDebug+1 ;;
+        :) fError "Value required for option: $OPTARG" $LINENO ;;
+        \?) fError "Unknown option: $OPTARG" $LINENO ;;
+    esac
 done
 let tOptInd=OPTIND-1
 shift $tOptInd
 if [ $# -eq 1 ]; then
-	gpFile="$1"
+    gpFile="$1"
 else
-	fError "Unknown options: $*" $LINENO
+    fError "Unknown options: $*" $LINENO
 fi
 
 # -------------------
diff --git a/bin/vid-new-project b/bin/vid-new-project
--- a/bin/vid-new-project
+++ b/bin/vid-new-project
@@ -1,11 +1,11 @@
 #!/bin/bash
 
 if [ $# -eq 0 -o "x$1" = "x-h" ]; then
-	cat <<EOF
+    cat <<EOF
 Usage:
 	vid-new-project ProjectName
 EOF
-	exit 1
+    exit 1
 fi
 
 # Todo:
@@ -24,28 +24,28 @@ echo "CVSROOT=$CVSROOT"
 # --------------------
 # Validate
 if [ ! -d /home/video ]; then
-	echo "Error: /home/video not found"
-	exit 1
+    echo "Error: /home/video not found"
+    exit 1
 fi
 if [ ! -d $CVSROOT/vid-template ]; then
-	echo "Error: $CVSROOT is not mounted."
-	exit 1
+    echo "Error: $CVSROOT is not mounted."
+    exit 1
 fi
 if [ -d /home/video/$gpProjName/CVS ]; then
-	echo "Warning: /home/video/$gpProjName already exists."
-	if [ -d $CVSROOT/$gpProjName ]; then
-		echo "Use: cvs update"
-	else
-		cat <<EOF
+    echo "Warning: /home/video/$gpProjName already exists."
+    if [ -d $CVSROOT/$gpProjName ]; then
+        echo "Use: cvs update"
+    else
+        cat <<EOF
 	But $CVSROOT/$gpProjName not found.
 	Mount the disk with "$gpProjName" project, then use: cvs update.
 EOF
-	fi
-	exit 1
+    fi
+    exit 1
 fi
 if [ -d $CVSROOT/$gpProjName ]; then
-	echo "Error: $CVSROOT/$gpProjName already exists."
-	exit 1
+    echo "Error: $CVSROOT/$gpProjName already exists."
+    exit 1
 fi
 
 # --------------------
@@ -54,8 +54,8 @@ fi
 cd $CVSROOT
 cp -r vid-template $gpProjName
 if [ ! -d $gpProjName ]; then
-	echo "Error: Problem creating: $CVSROOT/$gpProjName"
-	exit 1
+    echo "Error: Problem creating: $CVSROOT/$gpProjName"
+    exit 1
 fi
 cd /home/video
 cvs co $gpProjName
diff --git a/bin/vid-trim-rev b/bin/vid-trim-rev
--- a/bin/vid-trim-rev
+++ b/bin/vid-trim-rev
@@ -1,8 +1,8 @@
 #!/bin/bash
-# $Header: /repo/local.cvs/per/bruce/bin/vid-trim-rev,v 1.2 2020/09/18 20:54:21 bruce Exp $
+# $Header: /repo/local.cvs/per/bruce/bin/vid-trim-rev,v 1.3 2021/10/26 19:26:13 bruce Exp $
 
 if [ $# -ne 2 -o "x$1" = "x-h" ]; then
-	cat <<EOF
+    cat <<EOF
 Usage:
 	vid-rm-trim File Rel
 
@@ -17,7 +17,7 @@ Rel syntax:
 
 Note: this assumes you are on the same system that hosts the master files.
 EOF
-	exit 1
+    exit 1
 fi
 
 # --------------------
@@ -29,56 +29,56 @@ export gpRel=$2
 # Validate
 
 if [ ! -f $gpFile ]; then
-	echo "Error: could not find $gpFile"
-	exit 1
+    echo "Error: could not find $gpFile"
+    exit 1
 fi
 if [ ! -f CVS/Root ]; then
-	echo "Error: You are not in a CVS workspace."
-	exit 1
+    echo "Error: You are not in a CVS workspace."
+    exit 1
 fi
 
 export CVSROOT=$(cat CVS/Root)
 export cPath=$(cat CVS/Repository)
 
 if [ ! -f $CVSROOT/$cPath/${gpFile},v ]; then
-	cat <<EOF
+    cat <<EOF
 Error: could not find $CVSROOT/$cPath/${gpFile},v
 	Is $CVSROOT mounted?
 EOF
-	exit 1
+    exit 1
 fi
 
 echo
 tValid=$(echo $gpRel | tr -d '[0-9.:]')
 if [ -n "$tValid" ]; then
-	echo "Error: Rel can only contain: [0-9.:]"
-	exit 1
+    echo "Error: Rel can only contain: [0-9.:]"
+    exit 1
 fi
 tFound=0
 if [ ${gpRel#::} != $gpRel ]; then
-	echo "Notice: this will delete revisions before ${gpRel#::}"
-	tFound=1
+    echo "Notice: this will delete revisions before ${gpRel#::}"
+    tFound=1
 fi
 if [ ${gpRel%::} != $gpRel ]; then
-	echo "Notice: this will delete revisions after ${gpRel#::} including HEAD"
-	tFound=1
+    echo "Notice: this will delete revisions after ${gpRel#::} including HEAD"
+    tFound=1
 fi
 if [ $tFound -eq 0 -a ${gpRel#:} != $gpRel ]; then
-	echo "Notice: this will delete revisions before, and including ${gpRel#::}"
-	tFound=1
+    echo "Notice: this will delete revisions before, and including ${gpRel#::}"
+    tFound=1
 fi
 if [ $tFound -eq 0 -a ${gpRel%:} != $gpRel ]; then
-	echo "Notice: this will delete revisions after, and including ${gpRel#::} including HEAD"
-	tFound=1
+    echo "Notice: this will delete revisions after, and including ${gpRel#::} including HEAD"
+    tFound=1
 fi
 if [ $tFound -eq 0 -a ${gpRel#*::} != $gpRel ]; then
-	echo "Notice: this will delete revisions between,"
-	echo "but not including, the specified revisions."
-	tFound=1
+    echo "Notice: this will delete revisions between,"
+    echo "but not including, the specified revisions."
+    tFound=1
 fi
 if [ $tFound -eq 0 ]; then
-	echo "Notice: this only deletes revision $gpRel"
-	tFound=1
+    echo "Notice: this only deletes revision $gpRel"
+    tFound=1
 fi
 
 cat <<EOF
