Updated

diff --git a/bin/my-ip b/bin/my-ip
--- a/bin/my-ip
+++ b/bin/my-ip
@@ -3,45 +3,69 @@
 # Put "Include ~/.ssh/host.*.ip" at top of ~/.ssh/config file
 set -u
 
-logger -p user.info "my-ip running xxxxxxxxxxxxxxxxxxx"
+if [[ $# -ne 0 && "$1" = "-h" ]]; then
+    cat <<\EOF | more
+Usage: my-ip [-h]
 
-. sshagent -s
-pushd ~/.ssh >/dev/null 2>&1
+The version files in ~/.ssh will be updated, to get the IPs of the
+other computers on the LAN. Put the following line in your
+~/.ssh/config file:
+
+    Include ~/.ssh/host.*.ip
+
+This script will get the latest IP for this computer (usuallly a
+laptop). If the IP is different from what is in
+~/.ssh/host.$HOSTNAME.ip, the file will be updated with the new IP and
+it will be checked in.
+
+To check the IPs once an hour, put this in your crontab:
+
+    2 6-23 * * * ~/bin/my-ip
+
+Note: this assumes your ssh key is known by ssh-agent. See
+~/bin/sshagent
+
+EOF
+    exit 1
+fi
+
+logger -p user.info "my-ip running"
+
+# Set ssh key and get the latest IPs
+. sshagent -s >/dev/null
+set -u
+cd ~/.ssh >/dev/null
 timeout 30 cvs update
 if [[ $? -ne 0 ]]; then
-    logger -s -p user.warning "my-ip no-key-try-override xxxxxxxxxxxxxxxxxxx"
-    ~/.ssh/.override
-    . sshagent -s
-    timeout 30 cvs update
-    if [[ $? -ne 0 ]]; then
-        logger -s -p user.crit "my-ip cvs-update-failed xxxxxxxxxxxxxxxxxxx"
-        exit 1
-    fi
+    logger -s -p user.crit "my-ip cvs-update-failed"
+    exit 1
 fi
 chmod -R go= ~/.ssh/*
 
+# Get the latest IP for this computer
 cName=$(hostname -s)
 cConfig=~/.ssh/host.$(hostname -s).ip
 
 cIP=$(ifconfig | egrep 'inet 192\.168|inet 107\.220\.116' | head -n 1 | awk '{print $2}')
 if [ -z "$cIP" ]; then
-    popd >/dev/null 2>&1
-    logger -s -p user.warning "my-ip not-on-lan xxxxxxxxxxxxxxxxxxx"
+    logger -s -p user.warning "my-ip not-on-lan"
     exit 1
 fi
 echo "IP=$cIP"
 
+# Get the last saved IP for this computer
 cSavedIP=""
 if [ -f $cConfig ]; then
     cSavedIP=$(grep Hostname $cConfig | awk '{print $2}')
 fi
-##echo "SavedIP=$cSavedIP"
+##echo "Debug: SavedIP=$cSavedIP"
+
 if [ "$cIP" = "$cSavedIP" ]; then
-    popd >/dev/null 2>&1
-    logger -p user.info "my-ip no-change xxxxxxxxxxxxxxxxxxx"
+    logger -s -p user.info "my-ip no-change"
     exit 0
 fi
 
+# It is different, so update it IP file
 cat <<EOF >$cConfig
 Host $cName $cName.lan $cIP
         Hostname $cIP
@@ -52,9 +76,13 @@ Host $cName $cName.lan $cIP
         User bruce
 EOF
 chmod go= $cConfig
-cvs add $cName >/dev/null 2>&1
-cvs ci -m "Updated $cName"
-popd >/dev/null 2>&1
 
-logger -p user.notice "my-ip updated xxxxxxxxxxxxxxxxxxx"
+# If it is new, add it to CVS
+if ! grep -q "${cConfig##*/}" CVS/Entries; then
+    logger -s -p user.notice "my-ip add $cName"
+    cvs add ${cConfig##*/} >/dev/null 2>&1
+fi
+
+cvs ci -m "Updated $cName"
+logger -s -p user.notice "my-ip updated $cName"
 exit 0
diff --git a/bin/vid-edit b/bin/vid-edit
--- a/bin/vid-edit
+++ b/bin/vid-edit
@@ -195,7 +195,7 @@ kdenlive file's version.
 
 =head1 HISTORY
 
-$Revision: 1.44 $ $Date: 2025/10/25 21:48:54 $ GMT
+$Revision: 1.45 $ $Date: 2025/12/09 05:37:29 $ GMT
 
 =cut
 EOF
@@ -447,7 +447,14 @@ fFileCheck
 # Get KdenLive version, based on file's version
 export gKLProg
 if [[ "$gpVer" = "flatpak" ]]; then
-    gKLProg=$cKLBin/kdenlive-flatpak
+    gKLProg=$cKLBin/kdenlive.flatpak
+    if [[ ! -f  $gKLProg ]]; then
+        gKLProg=$cKLBin/kdenlive-flatpak
+    fi
+    if [[ ! -f  $gKLProg ]]; then
+        echo "Error: could not find: $gKLProg [$LINENO]"
+        exit 1
+    fi
 else
    fKLVer
 fi
